# Uncomment the next line to define a global platform for your project
platform :macos, '10.13'

target 'CocosBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocosBuilder
  pod 'Sparkle', '~> 1.23'
end
